events {}
http {
  limit_req_zone $binary_remote_addr zone=api_zone:10m rate=1200r/m;
  limit_req_zone $binary_remote_addr zone=login_zone:10m rate=10r/m;
  include /etc/nginx/mime.types;
  include /etc/nginx/conf.d/*.conf;
}
